### PR TITLE
fix fsm draft

### LINKED ISSUE #996: [BUG] opening an FSM automatically creates a draft without any edits

### PR DESCRIPTION
**Pull request by CerxMe**
closes #996

### CODE REVIEW

File: web/containers/InterfaceCreator/fsm/index.tsx [hunk 1]
```diff
@@ -461,14 +461,33 @@ const FSMView: React.FC<IFSMViewProps> = ({
...
+              const returnValue =
+                !value && !fsm[key]
+                  ? false
+                  : !isEqual(value, key === 'groups' ? fsm[key] || [] : fsm[key]);
+              console.log('HERE', key, returnValue);
+              return returnValue;
             }) || !isEqual(states, fsm.states)
           : true;
-
+        console.log('hasChanged', hasChanged);
```
Comment (Foxhoundn) [inline web/containers/InterfaceCreator/fsm/index.tsx:490]: Please remove logs

File: web/containers/InterfaceCreator/fsm/index.tsx [hunk 2]
```diff
@@ -461,14 +461,33 @@ const FSMView: React.FC<IFSMViewProps> = ({
...
     async () => {
+      console.log('input', inputCompatibility);
+      console.log('output', outputCompatibility);
+
       if (!embedded) {
         const draftId = getDraftId(fsm, interfaceId);
         const hasChanged = fsm
           ? some(metadata, (value, key) => {
-              return !isEqual(value, key === 'groups' ? fsm[key] || [] : fsm[key]);
+              console.log(
```
Comment (Foxhoundn) [inline web/containers/InterfaceCreator/fsm/index.tsx:471]: Please remove logs

**Review by Foxhoundn — CHANGES_REQUESTED** [review]
Please remove logs

**Review by Foxhoundn — APPROVED** [review]
