### PR TITLE
fixed fsm field wrapper

### LINKED ISSUE #993: [BUG] FSM fields wrapper is not collapsed when hidden
FSM fields wrapper is not collapsed when hidden

### PR DESCRIPTION
**Pull request by CerxMe**
closes #993

### CODE REVIEW

File: web/containers/InterfaceCreator/fsm/index.tsx [hunk 1]
```diff
@@ -1336,7 +1336,7 @@ const FSMView: React.FC<IFSMViewProps> = ({
       <div
         ref={fieldsWrapperRef}
         id="fsm-fields-wrapper"
-        style={{ height: '50%', overflowY: 'auto', overflowX: 'hidden' }}
+        style={{ height: !isMetadataHidden ? '50%' : undefined, overflowY: 'auto', overflowX: 'hidden' }}
```
Comment (Foxhoundn) [inline web/containers/InterfaceCreator/fsm/index.tsx:1339]: Nice

**Review by Foxhoundn — APPROVED** [review]
