### PR TITLE
Bugfix/3 6 3 fixes

### LINKED ISSUE #1000: [BUG] opening a pipeline immediately creates a draft
even though no changes are made

### LINKED ISSUE #1001: [BUG] mapper next button not enabled when all fields are assigned
image

### PR DESCRIPTION
**Pull request by CerxMe**
closes #1001
closes #1000

### CODE REVIEW

File: web/containers/InterfaceCreator/pipeline/index.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ import {
   deleteDraft,
   getDraftId,
   getTargetFile,
-  hasValue,
+  hasValue
```
Comment (Foxhoundn) [inline web/containers/InterfaceCreator/pipeline/index.tsx]: We use trailing commas everywhere, why was this removed?

**Review by Foxhoundn — APPROVED** [review]
